### ISSUE TITLE
Wrong index in bsplit

### ISSUE THREAD

**Issue by allo-** [nmoehrle/libacc#6]
I got another index error in [bvh_tree.h#L181](https://github.com/nmoehrle/libacc/blob/dcf3b3e068352b38fb04109ef50ad4fc7bd57b38/bvh_tree.h#L181)

    min = -5.00958252
    max = -5.00958014
    d = 0
    mid(aabb, d) - min = 2.4516127083984429e-06
    ((mid(aabb, d) - min) / (max - min)) * (NUM_BINS - 1) = 64.781696632504463
    idx = 64
    NUM_BINS = 64
    aabb.min = (-5.0095801960014716, 0.63644947007425456, 0.041062743939970059)
    aabb.max = (-5.0095799398356107, 0.64464411815625533, 0.054988806854231520)

**Comment by allo-** [comment]
Looks like a floating point issue to me, as min and max are float while my vector is double.
[Removed python code, which had wrong min/max from aabb]

**Comment by nmoehrle** [comment]
Both `(mid(aabb, d) - min)` and `(max - min)` are close to zero here but it should not have resulted in a value larger than one. But the debug mid in your example also does not hold `min <= mid <= max` so that might be the issue. That should be fixed by clamping, either here or in the computation of mid.

**Comment by allo-** [comment]
testing with doubles i got something closer to 0.99.
I am just not sure how stable the code is for small max-min anyway. When using double there it may just delay the crash until some variables are much closer again. Any idea how to avoid cancellation errors there?

**Comment by allo-** [comment]
According to https://stackoverflow.com/a/45367491/893159 this code will always work correctly, if the same floating point type is used.
